# Generated by Django 5.2.6 on 2025-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=100, unique=True)),
                ('Last_name', models.CharField(default='', max_length=100, unique=True)),
                ('Uname', models.CharField(default='', max_length=100)),
                ('mail', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
