# Generated by Django 5.2.6 on 2025-09-11 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('shelter', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('personality', models.JSONField(blank=True, default=list)),
                ('goodWith', models.JSONField(blank=True, default=list)),
                ('specialNeeds', models.JSONField(blank=True, default=list)),
                ('adoptionFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('images', models.JSONField(blank=True, default=list)),
                ('vaccinated', models.BooleanField(default=False)),
                ('spayedNeutered', models.BooleanField(default=False)),
                ('houseTrained', models.BooleanField(default=False)),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-datePosted'],
            },
        ),
    ]
