# Generated by Django 5.2.6 on 2025-09-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_alter_pet_goodwith_alter_pet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='pet/'),
        ),
    ]
