# Generated by Django 5.2.6 on 2025-09-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindVet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaryclinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clinics/'),
        ),
    ]
