# Generated by Django 5.2.6 on 2025-09-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindVet', '0002_veterinaryclinic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinaryclinic',
            name='general_practice',
        ),
        migrations.AddField(
            model_name='veterinaryclinic',
            name='specialties',
            field=models.TextField(default='', help_text='Comma-separated list of specialties'),
        ),
    ]
