# Generated by Django 5.2.6 on 2025-09-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindVet', '0003_remove_veterinaryclinic_general_practice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinaryclinic',
            name='services',
        ),
        migrations.AddField(
            model_name='veterinaryclinic',
            name='services',
            field=models.TextField(default='', help_text='Comma-separated list of specialties'),
        ),
    ]
