# Generated by Django 5.2.6 on 2025-09-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Category', models.CharField(choices=[('N', 'News'), ('Q', 'Question'), ('D', 'Discussion'), ('A', 'Announcement')], default='N', max_length=1)),
                ('Content', models.TextField(default='', max_length=100)),
                ('Tags', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
