# Generated by Django 5.2.6 on 2025-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_post_category_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
